# Generated by Django 3.1.2 on 2020-10-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPair',
            fields=[
                ('pair_id', models.CharField(help_text='HMAC-SHA256 of `<learner-email>|<mentor-email>` using key\nsettings.HISTORICAL_PAIR_KEY.', max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historical_pairs',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Date this pairing began')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='learner_pairing', to='participants.participant')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mentor_pairing', to='participants.participant')),
            ],
            options={
                'db_table': 'pairs',
            },
        ),
    ]
