# Generated by Django 3.1.2 on 2020-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField(help_text='The date that this information expires.  This can be extended (such as when\na pairing is made), and expiration is contingent on not being in a current\npair.  This field accomplishes the "lean data" practice of not keeping\nuser information forever. ')),
                ('email', models.EmailField(help_text="The participant's work email address.  This is used as a key. ", max_length=254)),
                ('role', models.CharField(choices=[('M', 'Mentor'), ('L', 'Learner')], help_text="The participant's role in the program.  Note that the same email may appear\nat most once in each role.", max_length=1)),
                ('full_name', models.CharField(help_text="The participant's full name (as they would prefer to be called).", max_length=512)),
                ('manager_email', models.EmailField(help_text="The participant's manager's email address.  This is used to verify approval. ", max_length=254)),
                ('approved', models.BooleanField(help_text='Whether this participant\'s participation has been approved by their manager.\nNull means "not yet"; we treat silence from managers as consent.')),
                ('time_availability', models.CharField(help_text="The participant's time availability, as a sequence of Y and N for each UTC hour,\nso `NNNYYYYYYYYYNNNNNNNNNNNN` indicates availability from 03:00-12:00 UTC.", max_length=12)),
                ('info', models.JSONField(help_text='Information about the participant that is not in another field.')),
            ],
            options={
                'unique_together': {('email', 'role')},
            },
        ),
    ]
