# Generated by Django 3.1.2 on 2020-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_availability',
            field=models.CharField(help_text="The participant's time availability, as a sequence of Y and N for each UTC hour,\nso `NNNYYYYYYYYYNNNNNNNNNNNN` indicates availability from 03:00-12:00 UTC.", max_length=24),
        ),
    ]
