# Generated by Django 3.1.2 on 2020-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20201013_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='info',
        ),
        migrations.AddField(
            model_name='participant',
            name='interests',
            field=models.JSONField(help_text="A learner's areas of interest, or a mentor's areas in which they can offer mentorship;\nformat is an array of open-text strings.", null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='org',
            field=models.CharField(help_text="Participant's organization (roughly, executive to whom they report)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='org_chart_distance',
            field=models.CharField(help_text='Preference for a pairing nearby or distant in the org chart (open text)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='org_level',
            field=models.CharField(help_text="Participant's current organizational level, e.g., `P3` or `M4`", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='time_at_org_level',
            field=models.CharField(help_text="Participant's time at current organizational level, e.g., `2-3 y`", max_length=10, null=True),
        ),
    ]
