# Generated by Django 3.1.2 on 2020-10-14 12:55

from django.db import migrations, models
import mentoring.participants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField(help_text='The date that this information expires.  This can be extended (such as when\na pairing is made), and expiration is contingent on not being in a current\npair.  This field accomplishes the "lean data" practice of not keeping\nuser information forever. ')),
                ('email', models.EmailField(help_text="The participant's work email address.  This is used as a key. ", max_length=254)),
                ('role', models.CharField(choices=[('M', 'Mentor'), ('L', 'Learner')], help_text="The participant's role in the program.  Note that the same email may appear\nat most once in each role.", max_length=1)),
                ('full_name', models.CharField(help_text="The participant's full name (as they would prefer to be called).", max_length=512)),
                ('manager', models.CharField(help_text="The participant's manager's name.", max_length=512)),
                ('manager_email', models.EmailField(help_text="The participant's manager's email address.  This is used to verify approval. ", max_length=254)),
                ('approved', models.BooleanField(help_text='Whether this participant\'s participation has been approved by their manager.\nNull means "not yet"; we treat silence from managers as consent.', null=True)),
                ('time_availability', models.CharField(help_text="The participant's time availability, as a sequence of Y and N for each UTC hour,\nso `NNNYYYYYYYYYNNNNNNNNNNNN` indicates availability from 03:00-12:00 UTC.", max_length=24, validators=[mentoring.participants.models.validate_time_availability])),
                ('org', models.CharField(help_text="Participant's organization (roughly, executive to whom they report)", max_length=100, null=True)),
                ('org_level', models.CharField(help_text="Participant's current organizational level, e.g., `P3` or `M4`", max_length=10, null=True)),
                ('time_at_org_level', models.CharField(help_text="Participant's time at current organizational level, e.g., `2-3 y`", max_length=10, null=True)),
                ('interests', models.JSONField(help_text="A learner's areas of interest, or a mentor's areas in which they can offer mentorship;\nformat is an array of open-text strings.", null=True, validators=[mentoring.participants.models.validate_interests])),
                ('track_change', models.CharField(help_text='Whether the participant is interested in changing tracks (between IC and Manager)', max_length=64, null=True)),
                ('org_chart_distance', models.CharField(help_text='Preference for a pairing nearby or distant in the org chart (open text)', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, help_text="Open comments from the participant's enrollment")),
            ],
            options={
                'db_table': 'participants',
                'unique_together': {('email', 'role')},
            },
        ),
    ]
