# Generated by Django 3.1.2 on 2021-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    def delete_all(apps, schema_editor):
        """
        As of adding this migration, this application has not yet been released, so deleting
        all participant data causes no harm and makes this migration simple.
        """
        Participant = apps.get_model('participants', 'Participant')
        Participant.objects.all().delete()

    operations = [
        migrations.RunPython(delete_all),
        migrations.AddField(
            model_name='participant',
            name='is_learner',
            field=models.BooleanField(default=False, help_text='True if this participant will act as a learner.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='True if this participant will act as a mentor.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(help_text="The participant's work email address.  This is used as a key. ", max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
    ]
