# Generated by Django 3.1.2 on 2021-01-25 16:22

from django.db import migrations, models
import mentoring.participants.models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20210125_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='interests',
        ),
        migrations.AddField(
            model_name='participant',
            name='learner_interests',
            field=models.JSONField(help_text="A learner's areas of interest; format is an array of open-text strings.", null=True, validators=[mentoring.participants.models.validate_interests]),
        ),
        migrations.AddField(
            model_name='participant',
            name='mentor_interests',
            field=models.JSONField(help_text="A mentor's areas in which they can offer mentorship; format is an array of open-text strings.", null=True, validators=[mentoring.participants.models.validate_interests]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='track_change',
            field=models.CharField(help_text='Whether a learner is interested in changing tracks (between IC and Manager)', max_length=64, null=True),
        ),
    ]
